id: I6FA2131F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:53:02+00:00'
last_modified: '2022-06-07T18:31:37.420116+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9407
  title: ཆོས་འབྱུང་བསྟན་པའི་པདྨ་རྒྱས་པའི་ཉིན་བྱེད། ༼ཤིང་པར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0E11:
      image_group_id: I1KG9459
      title: ''
      total_pages: 638
      order: 1
      base_file: 0E11.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
