id: P003229
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:55.751424
source_metadata:
  id: bdr:W1KG9407
  title: ཆོས་འབྱུང་བསྟན་པའི་པདྨ་རྒྱས་པའི་ཉིན་བྱེད། ༼ཤིང་པར།༽
  author: ''
  volumes:
    53acfeeb5c1c4080937595d33a80c772:
      image_group_id: I1KG9459
      title: ''
      volume_number: 1
      total_pages: 638
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
